ci:
  autofix_prs: false
  autoupdate_commit_msg: "pre-commit: bump repositories"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
        exclude: tests/packages/test-(bad-syntax|no-permission)/pyproject.toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.*]
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.8.3"
    hooks:
      - id: prettier
  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: v2.0.2
    hooks:
      - id: docstrfmt
        args: ["-l", "120"]
        additional_dependencies: ["sphinx>=9.1"]
        exclude: ^docs/index\.rst$ # https://github.com/LilSpazJoekp/docstrfmt/issues/176
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.2"
    hooks:
      - id: codespell
        args: ["-L", "sur"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: changelog-filenames
        name: Enforce towncrier fragment filenames
        files: ^docs/changelog/(?!([0-9]+\.(feature|bugfix|doc|removal|misc)\.rst|template\.jinja2|README\.rst)$).*
        entry: files in changelog must be valid (N.type.rst)
        language: fail
