ci:
  autofix_prs: false
  autoupdate_commit_msg: "pre-commit: bump repositories"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
        exclude: tests/packages/test-(bad-syntax|no-permission)/pyproject.toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # frozen: v0.25
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # frozen: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.*]
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "515f543f5718ebfd6ce22e16708bb32c68ff96e1" # frozen: v3.8.3
    hooks:
      - id: prettier
  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: 7653faa707cb660bc80cef0e8433932363b43504 # frozen: v2.0.2
    hooks:
      - id: docstrfmt
        args: ["-l", "120"]
        additional_dependencies: ["sphinx>=9.1"]
        exclude: ^docs/index\.rst$ # https://github.com/LilSpazJoekp/docstrfmt/issues/176
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 22f0422809455ec89ffdcf5a00170ba816e42ddb # frozen: v0.15.16
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/henryiii/flake8-lazy
    rev: 65b94e97b1091634368592d98072160842265fe4 # frozen: v0.8.2
    hooks:
      - id: flake8-lazy
        files: ^src/
  - repo: https://github.com/codespell-project/codespell
    rev: "2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a" # frozen: v2.4.2
    hooks:
      - id: codespell
        args: ["-L", "sur"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316" # frozen: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9 # frozen: v1.25.2
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]
  - repo: local
    hooks:
      - id: changelog-filenames
        name: Enforce towncrier fragment filenames
        files: ^docs/changelog/(?!([0-9]+\.(feature|bugfix|doc|removal|misc)\.rst|template\.jinja2|README\.rst)$).*
        entry: files in changelog must be valid (N.type.rst)
        language: fail
