name: checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install nox
      run: |
        pip install nox
        nox --version

    - name: Build the documentation
      run: nox -s docs
