name: check
on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install tox
        run: python -m pip install tox

      - name: Setup run environment
        run: tox -vv --notest -e docs

      - name: Run check for docs
        run: tox -e docs --skip-pkg-install
