name: type
on:
  workflow_call:
permissions: {}
jobs:
  type:
    name: Type check
    runs-on: ubuntu-26.04
    env:
      PY_COLORS: 1
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Python 3.15
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: false
          python-version: "3.15"
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Setup run environment
        run: tox -vv --notest -e type
      - name: Run check for type
        run: tox -e type --skip-pkg-install
