name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install pytest
      run: |
        pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov
        pytest --version

    - name: Install dependencies
      run: pip install toml pep517 packaging importlib_metadata

    - name: Install python2 dependencies
      if: ${{ matrix.python == 2.7 }}
      run: pip install typing

    - name: Run pytest
      run: pytest --verbose --cov --cov-report=xml

    - name: Send coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: PYTHON
