name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ${{ matrix.platform }}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        - macos
        - windows
        python:
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        - pypy3
        - pypy2

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up target Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pytest
      run: |
        pip install nox
        nox --version

    - name: Run tests (install via path)
      run: nox -s test-${{ matrix.python }} -- --run-integration

    - name: Run tests (run via PYTHONPATH)
      run: nox -s test_pythonpath-${{ matrix.python }} -- --run-integration

    - name: Run tests (install via wheel)
      run: nox -s test_wheel-${{ matrix.python }} -- --run-integration

    - name: Run tests (install via sdist)
      run: nox -s test_sdist-${{ matrix.python }} -- --run-integration

    - name: Send coverage report
      if: ${{ always() }}
      uses: codecov/codecov-action@v1
      env:
        PYTHON: ${{ matrix.python }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: PYTHON
