name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ${{ matrix.platform }}-latest
    strategy:
      matrix:
        platform: [ubuntu, macos, windows]
        python: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up target Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pytest
      run: |
        pip install nox
        nox --version

    - name: Run nox
      run: nox -s test-${{ matrix.python }}

    - name: Send coverage report
      uses: codecov/codecov-action@v1
      env:
        PYTHON: ${{ matrix.python }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: PYTHON
